using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Nucleus
{
    partial class Nucleus
    {

        static int export_bin2ida(string fname, Binary bin, List<DisasmSection> disasm, CFG cfg)
        {
            ulong entry;
            int i;

            using TextWriter f = File.CreateText(fname);
            if (f == null)
            {
                Log.print_err("cannot open file '{0}' for writing", fname);
                return -1;
            }

            f.WriteLine("\"\"\"");
            f.WriteLine("Script generated by {0}", NUCLEUS_VERSION);
            f.WriteLine("\"\"\"");
            f.WriteLine("");
            f.WriteLine("import idaapi");
            f.WriteLine("import idautils");
            f.WriteLine("import idc");
            f.WriteLine("");
            f.WriteLine("idaapi.autoWait()");
            f.WriteLine("");
            f.WriteLine("def mark_functions():");
            f.WriteLine("    functions = [");
            i = 0;
            foreach (var func in cfg.functions)
            {
                if (func.entry.Count == 0) continue;
                entry = func.entry.First().start;
                if ((i % 5) == 0) f.Write("        ");
                f.Write("0x{0:x}, ", entry);
                if ((++i % 5) == 0) f.WriteLine();
            }
            f.WriteLine("    ]");
            f.WriteLine("    for seg in idautils.Segments():");
            f.WriteLine("        if idaapi.segtype(idc.SegStart(seg)) != idaapi.SEG_CODE:");
            f.WriteLine("            continue");
            f.WriteLine("        for f in idautils.Functions(idc.SegStart(seg), idc.SegEnd(seg)):");
            f.WriteLine("            print 'nucleus: deleting function 0x%x' % (f)");
            f.WriteLine("            idc.DelFunction(f)");
            f.WriteLine("    for f in functions:");
            f.WriteLine("        print 'nucleus: defining function 0x%x' % (f)");
            f.WriteLine("        if idc.MakeCode(f):");
            f.WriteLine("            idc.MakeFunction(f)");
            f.WriteLine("");
            f.WriteLine("mark_functions()");

            return 0;
        }


        static int
        export_cfg2dot(string fname, CFG cfg)
        {
            BB bb;

            using TextWriter f = File.CreateText(fname);
            if (f == null)
            {
                Log.print_err("cannot open file '{0}' for writing", fname);
                return -1;
            }

            f.WriteLine("digraph G {");
            f.WriteLine();
            foreach (var kv in cfg.start2bb)
            {
                bb = kv.Value;
                foreach (var e in bb.targets)
                {
                    f.WriteLine("bb_{0} -> bb_{1} [ label=\"{2}\" ];", e.src.start, e.dst.start, e.type2str());
                }
            }
            f.WriteLine("}");
            return 0;
        }
    }
}
